<title>Abbreviations of Sources</title>

<h1>Abbreviations of Sources</h1>

<table>
<tr><th>BOP</th>  <td>Book of Praise, 1984, Canadian Reformed Churches</td>
</tr>
<tr><th>BoW</th>  <td>Book of Worship, 1990, Reformed Churches of Australia</td>
</tr>
<tr><th>Cyb</th> <td>www.cyberhymnal.org</td>
</tr>
<tr><th>NPH</th>  <td>Psalter Hymnal, 1978 (Grey book), Christian Reformed Church of North America</td>
</tr>
<tr><th>PH</th>  <td>Psalter Hymnal, 1976 (Blue book), Christian Reformed Church of North America</td>
</tr>
<tr><th>RPC</th>  <td>"The Book of Psalms for Singing", 1999.  Reformed Presbyterian Church of North America – similar title but completely different than Ward</td>
</tr>
<tr><th>Scots</th>  <td>"Sing Psalms", 2003.  Made by Free Church of Scotland.  Has modern language wordings available in soft copy.</td>
</tr>
<tr><th>Trin</th> <td>"Trinity Hymnal", 1961.  Orthodox Presbyterian Church</td>
</tr>
<tr><th>Ward</th>  <td>"The Complete Book of Psalms for Singing", 1991.  Roland Ward (Presbyterian Church of Eastern Australia) – similar title but completely different than RPC</td>
</tr>
</table>
