<h2>Hymnbook Committee Membership</h2>

<p>
 Please submit your queries and feedback to the secretary linked below. 
</p>

<h3>Committee Members</h3>
<ul>

<li>Lieda Brooks</li>

<li>John Goris</li>

<li><a href="email%3Fe=berwyn" onmouseover="e=&quot;berwyn&quot;+String.fromCharCode(64)+&quot;hymnal.ws&quot;; this.href=&quot;mai&quot;+&quot;lto:&quot;+e; this.firstChild.nodeValue=e;">Berwyn Hoyt (secretary & webmaster)</a></li>

<li>Lois Hoyt</li>

<li>John Rogers (Convenor)</li>
</ul>
 

<h3>Additional help</h3>

<ul>
<li>Jessica Gough (projection slides)</li>

<li>Lois Hoyt (proofing)</li>

<li>Lydia Nugteren (typesetting)</li>

<li>Rebekah de Ruiter (typesetting)</li>

<li>Ben Post (copyrights)</li>

<li>Pieter van der Wel (proofing)</li>
</ul>
