<h2>Contributions</h2>

<p>
 We have had a number of submissions and these have been very valuable.  Some have suggested just one song, while others have pointed us to a
number of songs.  A number of people have helpfully provided feedback in the form of corrections, complaints or recommendations of specific
wordings or music.  Such specific feedback has been valuable to us.  Send your feedback to
<a href="email%3Fe=admin"
onmouseover="e=&quot;admin&quot;+String.fromCharCode(64)+&quot;hymnal.ws?subject=NZPH%20Feedback&amp;body=Songs you are commenting about:%0D%0A%0D%0AComments and reasons:%0D%0A%0D%0A%0D%0AGive alternatives:%0D%0A&quot;; this.href=&quot;mai&quot;+&quot;lto:&quot;+e;">
Berwyn Hoyt (secretary & webmaster)</a>
</p>

<p>
 One <b>very easy</b> way for you to contribute is to help get the word around by emailing a link to this website to your church friends. Click <a href="mailto:friend?subject=New%20Zealand%20Psalter%20Hymnal%20Website?&amp;body=Look%20at%20this:%20http://

hymnal.rcnz.org.nz">mailto:friend</A>
</p>

<p>
 Besides personal submissions to the committee, below are some other significant ways you can contribute.
</p>

<h3>Contribute by Careful Selection</h3>

<p>
 Another way to contribute would be to get together in a group with others to carefully select songs from a wider variety of sources than the ones we already sing from.
</p>

<p>
 For more information, see the <a href='Committee.htm'>contact list</a>.
</p>

<h3>Contributors</h3>

<p>
 We would like to thank the following people from the Reformed Churches of New Zealand who have already provided us with contributions:
</p>

<ul>
<li>Matthew Bartlett (Wellington)</li>

<li>Dave and Andrea Benfell (Bishopdale)</li>

<li>Debbie Bennet (Hamilton)</li>

<li>John Biersteker (Levin)</li>

<li>Henk Bosma (Bishopdale)</li>

<li>Lieda Brooks (Hamilton)</li>

<li>Helen Capill (Bishopdale)</li>

<li>James Cho (North Shore)</li>

<li>Coby Cressy (Hamilton)</li>

<li>Marinda de Villiers (North Shore)</li>

<li>Christina Flinn (North Shore)</li>

<li>John Goris (Wellington)</li>

<li>Heather Hard (Mangere)</li>

<li>Liana Havelaar (Christchurch)</li>

<li>John Haverland (Pukekohe)</li>

<li>John Holtslag (Silverstream)</li>

<li>Berwyn Hoyt (North Shore)</li>

<li>Benjamin Hoyt (Masterton)</li>

<li>Lois Hoyt (Hastings)</li>

<li>Jocelyn Jaquiery (Dunedin)</li>

<li>Jim Kloeg (Hamilton)</li>

<li>Bernie Kramer (Hastings)</li>

<li>Ron Newton (Dunedin)</li>

<li>Lydia Nugteren (Wellington)</li>

<li>John Rogers (North Shore)</li>

<li>Peter and Rona Rose (Hamilton)</li>

<li>Aart Snoek (Wellington)</li>

<li>Patricia van Laar (Palmerston)</li>

<li>Laurel van Wichen (Bishopdale)</li>

<li>Lenie van Wichen (North Shore)</li>

<li>Rob and Andrea Vosslamber (Hastings)</li>

<li>Jacqui Voschezang (North Shore)</li>

<li>Rosalie Welsh (Avondale)</li>

<li>Bill Wiersma (Hamilton)</li>

<li>Willemse Family (Hamilton)</li>
</ul>

<h3>And the following churches:</h3>

<ul>
<li>Reformed Church of Dovedale</li>

<li>Reformed Church of Hastings</li>

<li>Reformed Church of Nelson</li>
</ul>
