<h2>Contributions</h2>

<p>
 We have had a number of submissions and these have been very valuable.  Some have suggested just one song, while others have pointed us to a
number of songs.  A number of people have helpfully provided feedback in the form of corrections, complaints or recommendations of specific
wordings or music.  Such specific feedback has been valuable to us.  Send your feedback to
<a href="email%3Fe=admin"
onmouseover="e=&quot;admin&quot;+String.fromCharCode(64)+&quot;hymnal.ws?subject=NZPH%20Feedback&amp;body=Songs you are commenting about:%0D%0A%0D%0AComments and reasons:%0D%0A%0D%0A%0D%0AGive alternatives:%0D%0A&quot;; this.href=&quot;mai&quot;+&quot;lto
:&quot;+e;">
Elrike Hoyt (administrator)</a>
</p>

<p>
 For more information, see the <a href='Committee.htm'>contact list</a>.
</p>

<h3>Contributors</h3>

<p>
 We would like to thank the following people from the Reformed Churches of New Zealand who have already provided us with contributions:
</p>

<ul>

<li>Lynton Baird (Wellington)</li>
<li>Matthew Bartlett (Wellington)</li>
<li>Dave and Andrea Benfell (Bishopdale)</li>
<li>Debbie Bennet (Hamilton)</li>
<li>John Biersteker (Levin)</li>
<li>Henk Bosma (Bishopdale)</li>
<li>Liz Bouda (Hamilton)</li>
<li>Lieda Brooks (Hamilton)</li>
<li>Helen Capill (Bishopdale)</li>
<li>James Cho (North Shore)</li>
<li>Sjirk Couperus (Hastings)</li>
<li>Coby Cressy (Hamilton)</li>
<li>Sally Davey (Dovedale)</li>
<li>Rebekah de Ruiter (Bishopdale)</li>
<li>Marinda de Villiers (North Shore)</li>
<li>Jeen de Vries (Hastings)</li>
<li>Henk den Hartig (Hamilton)</li>
<li>Paul Goodenough (North Short)</li>
<li>Christina Flinn (North Shore)</li>
<li>John Goris (Wellington)</li>
<li>Jessica Gough (Cornwall St)</li>
<li>Ella Griffin</li>
<li>Gysbertson Family(Masterton)</li>
<li>Heather Hard (Mangere)</li>
<li>Liana & Ed Havelaar (Christchurch)</li>
<li>John Haverland (Pukekohe)</li>
<li>Andre Holtslag (Dovedale)</li>
<li>John Holtslag (Silverstream)</li>
<li>Ben Hoyt (Masterton)</li>
<li>Berwyn Hoyt (North Shore)</li>
<li>Bruce Hoyt (Oamaru)</li>
<li>Elrike Hoyt (Dovedale)</li>
<li>Lois Hoyt (Oamaru)</li>
<li>Veronica Hoyt (Dovedale)</li>
<li>Cathy Irons (Bishopdale)</li>
<li>Jocelyn Jaquiery (Dunedin)</li>
<li>Gerald Kleinjan (Silverstream)</li>
<li>Jim Kloeg (Hamilton)</li>
<li>Michael Kloeg (Masterton)</li>
<li>Bernie Kramer (Hastings)</li>
<li>Ron Newton (Dunedin)</li>
<li>Lydia & Andrew Nugteren (Wellington)</li>
<li>Leslie Pijpker (Dunedin)</li>
<li>Eddie Poot (Hamilton)</li>
<li>John Rogers (North Shore)</li>
<li>Peter and Rona Rose (Hamilton)</li>
<li>Bruno Saathof (Hastings)</li>
<li>Craig Smith (Palmerston North)</li>
<li>Aart Snoek (Wellington)</li>
<li>Patricia van Laar (Palmerston North)</li>
<li>Bert & Fo van Ameyde (Bishopdale)</li>
<li>Jake van der Burg (Nelson)</li>
<li>Laurel van Wichen (Bishopdale)</li>
<li>Lenie van Wichen (North Shore)</li>
<li>Esther Verbokkem (Hastings)</li>
<li>Nel Visser (Palmerston North)</li>
<li>Jacqui Voschezang (North Shore)</li>
<li>Rob & Andy Vosslamber (Hastings)</li>
<li>Dilys Watson (Dovedale)</li>
<li>Neville and Soesi Watson (Bishopdale)</li>
<li>Rosalie Welsh (Avondale)</li>
<li>Bill Wiersma (Hamilton)</li>
<li>Willemse Family (Hamilton)</li>

</ul>

<p>And a number of churches have also contributed.</p>
