
<h2>Copyright info</h2>

<p>
 Some of the music and song text presented on this website are copyright.  Elements that are copyright have a copyright holder listed at the bottom of the page.  Note that music and text are independently copyrighted &ndash; that is, if either has no copyright holder listed, then that text or that music is public domain and may be copied and altered without permission.
</p>
 
<p>
 Copyrighted works presented here may be copied only according to the following details as required by each copyright holder:
</p>

<p>
 <b>CRC Publications:</b> These are for use purely for evaluation for a 5 year term or until our final version of hymnal is published.
</p>

<p>
 <b>Helder, William:</b> These are for private use only and for public use purely for evaluation.
</p>

<p>
 <b>Hope Publishing Co.:</b> May not be presented or copied.  Contact copyright holder.
</p>

<p>
 <b>Jubilate Hymns:</b> May not be presented or copied.  Contact copyright holder.
</p>

<p>
 <b>Oxford University Press:</b> May not be presented or copied.  Contact copyright holder.
</p>

<p>
 <b>Psalmody Committee, Free Church of Scotland:</b> These are for private use only and for public use purely for evaluation until the final publication in book form is available.
</p>

<p>
 <b>RCNZ Hymnal Committee:</b> May be freely copied and used but permission must be requested for alterations.
</p>

<p>
 <b>Scripture in Song:</b> May not be presented or copied.  Contact copyright holder.
</p>

<p>
 <b>Ward, Rowland S.:</b> These are for private use only and for public use purely for evaluation until the final publication in book form is available.  They are taken by permission from The Complete Book of Psalms for Singing with Study Notes (published 1991 by the Presbyterian Church of Eastern Australia, 358 Mountain Hwy, Wantirna, Victoria 3152).  Those listed as &ldquo;alt.&rdquo; have been altered with the kind permission of Rev Dr Rowland S. Ward, the copyright holder.  
</p>
