
	<TITLE>It's In a Book</TITLE>

<h2>It&rsquo;s in a Book</h2>

<p>
 Having our hymnody in a single book has several advantages:
</p>
 
<ul>
<li>It will have words and music - which is of great value for congregational singing, especially for our denomination where people love to sing in parts.</li>
<li>It lets us take our worship music home with us. No other form of presentation is as well suited for use in the home. Many of our families maintain singing traditions at home, which we hope the new book will encourage.</li>
</ul>

<p>
 Our culture separates life into &lsquo;religion&rsquo; and &lsquo;real life&rsquo;. By contrast, biblical Christianity affects our whole life. Being able to easily bring the songs of God home from Church can help us worship God outside of Sunday services, and help us to:
</p>

<p>
 <i>&ldquo;Let the word of Christ richly dwell within you, with all wisdom, teaching and admonishing one another with psalms and hymns and spiritual songs, singing with thankfulness in your hearts to God.&rdquo;</i> (Colossians 3:16)
</p>
