
<title>Synodical Mandate</title>

<h2>Mandate of the Hymnbook Committee</h2>

<p>
<b> The following is an extract from the minutes of the 2002 Synod of the Reformed Churches of New Zealand:</b>
</p>


<p>
 Synod approved the following mandate for the Psalm and Hymn Selection Committee:
 </p>

<i>
<ol>
<li>   Select Psalm versions that are as faithful as possible in content and form of expression to Scripture, granting proper room for poetical necessity.</li>
<li>   Psalm and Bible song selections are to be evaluated for the soundness of their paraphrasing against the relevant sections in the synodically approved Bible versions (NIV and NASB).</li>
<li>
 Provide a reasonably large selection of hymns and songs to take into account the various preferences in our churches, namely, those resulting from our cultural mix, age differences, etc. In this regard, the committee should note the following:
 <ul>
    <li>      Where Genevan tunes are presented, the committee is to consider providing a non-Genevan alternative.</li>
    <li>      The committee is to solicit contributions from a wide cross-section of our membership. (This is to help the committee in its selection task and to gain a better feel for the preferences of our members. However, while all contributions will
              receive due consideration, the committee is not bound by the act of contribution.)</li>
    <li>       In respect of updating language, the committee is to leave well alone by and large and change only when necessary for meaning.</li>
    <li>      The committee will not attempt any writing of its own.</li>
    <li>       As far as possible, Psalm, hymn and song selections are to be taken from our present approved and provisionally approved sources.</li>
 </ul>
</li>
<li>The committee has power to co-opt other personnel for specific tasks.</li>
</ol>
</i>

<p>
 <b>The following is an extract from the minutes of the 2005 Synod of the Reformed Churches of New Zealand:</b>
 </p>


<p>
 <b>Synod decided</b>
 </p>

<ol>
   <li><i>To charge the Psalm & Hymn Selection Committee to continue its work as mandated by Synod 2002.</i></li>
   <li>
    <i>To affirm that the ultimate goal of the committee is to produce a book of Psalms and hymns with musical scores and lyrics along the lines of the committee's work so far.</i>
    <br /><br />
    <i>Note: This is a statement of synod's intention. The committee is not being mandated at this time to produce a book.</i>
    <br /><br />
    Grounds:
    <ol>
     <li>It was the intention of Synod 2002 ultimately to make a book available for use in the churches.</li>
     <li>It will be easier to obtain copyright permissions for use in homes and for public display if copyright holders can be assured of a future printing.</li>
     <li>Assurance of a future printing may also make it easier to obtain permission to use the Psalms and hymns in various forms (photocopied, OHP, data projected) in the interim.</li>
    </ol>
   </li>

   <li>
    <i>That computer CDs for use in the churches be produced including:</i>
    <ul>
     <li><i>Musical scores with words in a format suitable for photocopying.</i></li>
     <li><i>Words without scores in a format suitable for public projection or photocopying.</i></li>
    </ul>
    <i>Note: this may incur additional copyright fees.</i>
    <br /><br />
    Grounds:
    <ol>
     <li>Several churches have expressed a strong desire to begin using the Psalms and hymns produced by the committee before a book is finally produced.</li>
     <li>Such CDs are easy to produce as a by-product of what the committee is already doing.</li>
     <li>The only costs involved are the copyrights and the small cost of a blank CD.</li>
    </ol>
   </li>

   <li>
    <i>That computer CDs for use in homes be produced including:</i>
    <ul>
     <li><i>Musical scores with words in a format suitable for printing or displaying on a computer screen.</i></li>
     <li><i>Files (e.g. midi files) playable on the computer to accompany singing in the home.</i></li>
    </ul>
    Grounds:
    <ol>
     <li>This will give church leaders a tool to enable every family with a computer to worship God in song even where no one in the family can play a musical instrument.</li>
     <li>It will also enable homes with musical talent to play the music and sing in 4-part harmony.</li>
    </ol>
   </li>

   <li>
    <i>That copyright permissions be obtained and paid for by the Synodical Treasurer (for the above uses and/or for the first print run, whichever is best).</i>
    <br /><br />
    <i>Note 1: A rough estimate of copyright costs for the complete printed book of Psalms and hymns is $1 to $1.50 per copy.</i>
    <br />
    <i>Note 2: In order to use the Psalms and hymns in the interim, the best way to pay for copyright costs may be to pay these for the first print run up front. If we assume a first print run of 3000 at $1 per copy, this will be $3000.</i>
    <br /><br />
    Grounds:
    <br />
    <ul>
     <li>In the long run, all churches will benefit from either the printed books or the CDs and all homes will benefit from the CDs. Therefore the copyright costs should be paid for by the Synodical Treasurer.</li>
    </ul>
   </li>
   <li><i>To approve the use of the committee's Psalm selection for provisional use in the churches for evaluation.</i></li>
   <li><i>To adopt Statement of Principle (cf. Report 12, Appendix) for inclusion in the proposed new psalter-hymnal.</i></li>
</ol>


<p>
 <b>The following is an extract from the minutes of the 2008 Synod of the Reformed Churches of New Zealand:</b>
 </p>


<p>
 <b>Synod decided</b>
 </p>

<i><ol>
   <li> To charge the Psalm & Hymn Selection Committee to continue its work as mandated by Synods 2002 & 2005 with a view to: </li>
   <ol>
    <li> final approval of Psalm and hymn selections in 2011; and </li>
    <li> authorisation of publication in 2011. </li>
   </ol>
   <li> To request the Churches to use and study the provisional Psalm selection and give
        feedback with any suggestions and/or criticisms to help the committee improve the
        selection where thought possible or necessary.
   </li>
</ol></i>

<p>
 Rev. Rogers commended to the churches the <i><a href='Introduction.pdf'>Introduction to Sing to the Lord (Provisional) for
 Ministers and Musicians</a></i> written by Mrs. Lieda Brooks.
 </p>

<p>
 He sought clarification with regard to the statement in the mandate of the committee &ldquo;not to include
 original material&rdquo; and asked for permission to do so after all. Synod gave its permission to include
 original material by common consent.
 </p>

<p>
 <b>Synod decided</b>
 </p>
<i><ol>
    To express its thanks to the committee for the work done so far.
</ol></i>

<p>
 The moderator instructed the stated clerk to put this in writing to the committee.
</p>
