<h2>Resources for musicians</h2>

<p>
 You can now download the
 <a href='Sing to the Lord tune Index.xls'>Sing to the Lord Tune Index</a>
 as a spreadsheet.
</p>

<p>
 We also have and excellent <a href='Introduction.pdf'>handbook for ministers and musicians</a>
 that includes hints on accompaniment and a guide to introducing the new Psalm settings
 to your congregation.  If you want, there are spare printed copies available from
 <a href="email%3Fe=admin" onmouseover="e=&quot;admin&quot;+String.fromCharCode(64)+&quot;hymnal.ws&quot;; this.href=&quot;mai&quot;+&quot;lto:&quot;+e; this.firstChild.nodeValue=e;">Lieda Brooks</a>
</p>
