<h1>Projection of Songs for Public Singing</h1>

$update

<p>
We plan to make powerpoint slides of all the
songs in this hymnbook project. Below is copyright information that you
need to know to project these songs for public singing. </p>

<blockquote>
 Note: this page only applies to projection for public singing, as permissions
 have <i>already</i> been obtained for full public use of the print publication
 <i>Sing to the Lord (provisional)</i>.
</blockquote>

<h3>Psalm Projection Slides</h3>

<p>
Almost all of the Psalm slides may be used by the Reformed Churches of 
New Zealand free of charge: we have either been given permission or, for
a few, we have paid for it.  You can download the
<a href='Songs/slides/slides.zip'>Psalm slides here</a>.
But note that we have not been able to obtain
permission to project Psalms 57b or 139 at all. </p>

<p>
Only churches with CCLI licenses can project Psalm 57b, and no-one
may project Psalm 139:1-3. For churches in the RCNZ, these are the
only remaining Psalms with projection limitations. </p>

<p>
Note that a number of these do require special notes to be placed on the slides
as we have done.  If you make up your own slides, then you will also have to place
these notes.  Here is the <a href='New_slide_credit_texts_April2012.pdf'>full list of songs
and special notes</a>. </p>

<p>
If you are not in the Reformed Churches of New Zealand then you will have to obtain
your own permission if you wish to project any of the
<a href='New_slide_credit_texts_April2012.pdf'>Psalms listed here</a>.

<h3>Hymn Projection Slides</h3>

<p>Coming ...</p>

<p><small>[Updated $date.]</small></p>
$update
