<h2>Projection of Songs for Public Singing</h2>

$update

<p>
 We plan to making powerpoint slides of all the songs in this hymnbook
project. Below is copyright information that you need to know to project
these songs for public singing. </p>

<blockquote>
 Note: this page only applies to projection for public singing. Permissions
 have already been obtained for full public use of the print publication
 <i>Sing to the Lord (provisional)</i>.
</blockquote>

<p>
 Most of these may be used by anyone free of charge. However, a few of
these are currently subject to special handling. In particular, the
following may only be projected if your church holds a CCLI copyright
licence, and their use must be reported to the <a
href='http://www.ccli.com/'>CCLI</a> annually. </p>

<p>
 <b>May be projected if reported via <a href='http://www.ccli.com/'>CCLI</a>:</b>
 </p>

<blockquote>
 1b, 5, 6, 7, 13, 14, 16, 25, 26, 42, 48, 50, 53, 57b, 59, 64,
 65, 66, 69, 79, 86, 86b, 88, 89, 89b, 94, 102, 103, 108, 119v16,
 137b, 143, 144, 154
</blockquote>

<p>
 In addition, some songs which are not available elsewhere on this website
for copyright reasons are now available in our <i>Sing to the Lord
(provisional)</i> psalter. We have not yet received permission to project
these for public singing. In upcoming months we will be working with
copyright holders to obtain permission to project these songs also, so
check back here periodically for updates: </p>

<p>
 <b>May not yet be projected:</b>
</p>

<blockquote>
 2, 16b, 21, 27, 37, 39, 52, 60, 78b, 119v41, 119v169, 131, 139, 145, 149, 150
</blockquote>

<p>
 <b>All the rest may be projected free of charge.</b>
</p>

<p>Lists dated $date.</p>
$update

<h3>PowerPoint Slides</h3>

<p>
 <b>Coming soon! (October)</b>
</p>
