<h2>Scripture Memory</h2>

 <p>
 The following features of the Scripture sections of our new hymnal are intended to make memorisation of scripture easier by:
 </p>
 

<ul>
    <li>Numbering songs by <b>Psalm number</b>: 1a, 1b, 2a, ...</li>
    <li>Using words that <b>follow Scripture</b> more closely while maintaining the poetry.</li>
    <li><b>Updating the language.</b></li>
    <li><b>Retaining the good tunes</b> from our current hymnal and <b>replacing</b> the poor ones.</li>
    <li>Providing one <b>main tune</b> for each Psalm, together with a <b>summary psalm or alternate tune</b> where appropriate.</li>
</ul> 

<p>
 This helps to associate one specific tune with each Psalm, which aids our memory of the Psalms and other Scripture – especially with more accurate translations.
 </p>
 

<p>
 It is hoped this will become a valuable resource for teaching our children the Scriptures.  (For example, some Christian schools have used songs as a means of easy Scripture memorization.)
 </p>
