$cdheader

<p>
 Here we present a work in progress by a committee appointed by the 2002
 Synod of the Reformed Churches of New Zealand.  The committee's mandate is
 to:
 </p>

<ol>
 <li>Select poetic Psalm versions faithful to Scripture.</li>
 <li>Select hymns in significant quantity for the various preferences in our churches.</li>
 <li>Solicit contributions from a wide cross-section of our membership.</li>
</ol>

<p style='text-align: right'>
(<Click here for the <a href='Mandate.htm'>full mandate</a> and the <br />
Commitee Reports to Synods <a href='Report to Synod 2005.pdf'>2005</a>
and <a href='Report to Synod 2008.pdf'>2008</a>)


<h3>Progress</h3>

$update

<p>
 In October 2008, we saw the arrival of the provisional
 printing of the psalter: <i>Sing to the Lord (provisional)</i> and it has been
 well-received with orders surpassing 2000 copies.  Do make sure to get
 your copy of the <i><a href='Introduction.pdf'><font color='DarkRed'>Introduction to Sing to the Lord</font></a>.</i>
 </p>

<p>
 The committee has
 now embarked on the second stage of this project, the selection of hymns
 for the final hymnal. As we complete our proof reading, these will become
 <a href='http://hymnal.ws/public/Songs.htm'>available here</a> on the public website.
 </p>

<p>
 If you are interested in the name of the hymnal, check out this little <a href="Name.htm">bit of history</a>.
 </p>

<h3>Features</h3>

<p>
 The Synod plans to publish this as a <a href='In a
 Book.htm'><b>book</b></a>, and has adopted this <a href='Statement of
 Principle.doc'>statement of principle</a> for the purpose. To help enhance
 our appreciation of the Psalms, these are the features of the <b>Psalms
 Section:</b>
</p>

<ul>
      <li>Number the songs by <b>Psalm number</b>: 1a, 1b, 2a, ...</li>
      <li>Choose words which <b>follow Scripture</b> more closely, while maintaining the poetry.</li>
      <li><b>Use up-to-date language</b> in most selections.</li>
      <li><b>Retain the good tunes</b> from our current hymnal and <b>replace</b> the poor ones.</li>
      <li>Choose one <b>main tune</b> that covers the whole Psalm, with a <b>summary psalm or alternate tune where appropriate.</b></li>
      <li>Most of these changes help with <a href='Scripture Memory.htm'>memorising Scripture (click)</a>.</li>
</ul>
In the <b>Hymns section</b> we plan to:

<ul>
      <li><b>Retain</b> good and well-loved hymns and <b>replace</b> the poor hymns.</li>
      <li><b>Add hymns</b> according to the variety of preferences in our churches (we need <a href='Contributions.htm'>your help</a>).</li>
      <li><b>Update language,</b> but only where necessary for meaning.</li>
</ul>
<h3>Contacts</h3>

<p>
 Here is the <a href='Committee.htm'>committee membership</a> and contact list.
 </p>
