<h2>1. Score Loading Issue</h2>

<p>
If you get the following message when trying to view a score, you will need to upgrade your version of the Scorch player:
</p>
<img src='images/support/image002.jpg' />
  
<h2>2. Upgrading your Scorch Player</h2>

<p>
The following procedure will work if you use Internet Explorer as your web browser.  If you use Firefox, you will need to follow a slightly different procedure.  Please email the website <a href='mailto:bvhoyt@gmail.com'>Administrator</a> if you can't figure it out.
</p>

<ol>
   <li>Make sure that you have closed your web browser.</li>
   <li>
    To fix this, download the latest scorch program by browsing to or clicking on: <a href='http://www.sibelius.com/download/software/win/InstallScorch.exe'>http://www.sibelius.com/download/software/win/InstallScorch.exe</a>
   </li>
   <li>
    You should see the following message appear:
    <br /><br />
    <img src='images/support/image004.jpg' />
    <br />
    Click 'Run'.  This could take a few minutes while it downloads the new software.
   </li>
   <li>
    Next, you might see a message that says:
    <br /><br />
    <img src='images/support/image006.jpg' />
    <br />
    If you see that, click 'Run' again.
   </li>

   <li>
    When you see the following message, click 'Next':
    <br /><br />
    <img src='images/support/image008.jpg' />
   </li>
 

   <li>
    When you see the following message, click 'I Agree':
    <br /><br />
    <img src='images/support/image010.jpg' />
   </li>
 

   <li>
    You are done.  Now try to view the score again and it should work fine.
   </li>
</ol>
